
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import creator

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("600x480")
window.configure(bg = "#DBD2FF")
window.title("PyBlogger Creator")



canvas = Canvas(
    window,
    bg = "#DBD2FF",
    height = 480,
    width = 600,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    189.0,
    8.0,
    anchor="nw",
    text="PyBlogger",
    fill="#000000",
    font=("JejuGothic", 48 * -1)
)

canvas.create_text(
    222.0,
    60.0,
    anchor="nw",
    text="creator",
    fill="#000000",
    font=("JejuGothic", 48 * -1)
)

canvas.create_text(
    47.0,
    196.0,
    anchor="nw",
    text="Source:",
    fill="#000000",
    font=("Jaldi Regular", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    306.5,
    240.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#361F49",
    fg="#ffffff",
    highlightthickness=0
)
entry_1.place(
    x=47.0,
    y=225.0,
    width=519.0,
    height=28.0
)

canvas.create_text(
    47.0,
    132.0,
    anchor="nw",
    text="Name of project:",
    fill="#000000",
    font=("Jaldi Regular", 20 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    306.5,
    176.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#361F49",
    fg="#ffffff",
    highlightthickness=0
)
entry_2.place(
    x=47.0,
    y=161.0,
    width=519.0,
    height=28.0
)

canvas.create_text(
    47.0,
    262.0,
    anchor="nw",
    text="Colors:",
    fill="#000000",
    font=("Jaldi Regular", 20 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    111.0,
    309.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#361F49",
    fg="#ffffff",
    highlightthickness=0
)
entry_3.place(
    x=47.0,
    y=294.0,
    width=128.0,
    height=28.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    112.0,
    379.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#361F49",
    fg="#ffffff",
    highlightthickness=0
)
entry_4.place(
    x=48.0,
    y=364.0,
    width=128.0,
    height=28.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    111.0,
    344.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#361F49",
    fg="#ffffff",
    highlightthickness=0
)
entry_5.place(
    x=47.0,
    y=329.0,
    width=128.0,
    height=28.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: creator.criar_blog(entry_2.get()),
    relief="flat"
)
button_1.place(
    x=397.0,
    y=394.0,
    width=169.0,
    height=59.0
)


window.resizable(False, False)
window.mainloop()
